name: Run_test

on:
  pull_request:
    branches: [main,master]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        run: gradle/gradle-build-action@v2

      - run: ./gradlew ktlintCheck


