name: Android CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build jacocoTestReport
      - name: Run unit tests
        run: ./gradlew test
      - name: Run Ktlint
        run: ./gradlew ktlint
      - name: Upload Ktlint report
        uses: actions/upload-artifact@v4
        with:
          name: Ktlint Report
          path: app/build/reports/ktlint
      - name: Publish JUnit test results
        if: always()
        uses: junit-team/junit-report-builder@v4
        with:
          report-files: '**/TEST-*.xml'
      - name: Publish HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Reports
          path: app/build/reports/tests/testDebugUnitTest/index.html



#name: Run_test
#
#on:
#  pull_request:
#    branches: [main,master]
#
#jobs:
#  ktlint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: 17
#
#      - name: Setup Gradle
#        run: gradle/gradle-build-action@v2
#
#      - run: ./gradlew ktlintCheck


